### ISSUE TITLE
Repository doesn't have a LICENSE file

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.epfl.ch#13]

**Comment by SethTisue** [comment]
@heathermiller is this something we could do a quick fix on? is there an appropriate license file I could drop in?

**Comment by SethTisue** [comment]
@heathermiller sorry to nag, but I would really like to take care of this

**Comment by heathermiller** [comment]
Should just be the Scala license. I'll add it now.

**Comment by heathermiller** [comment]
Done: https://github.com/scala/scala.epfl.ch/blob/master/LICENSE.md
