### ISSUE TITLE
No links to Coursera in the Education section

### ISSUE THREAD

**Issue by dwijnand** [scala/scala.epfl.ch#16]
I wanted to link the Scala Coursera courses to a student of Scala, but I wanted to do it via the Scala Center so they became aware of SC too.

Sadly nothing in the Education section actually links to the courses or the specialisation. You have to take what you see and Google it up, if you don't give up already.

![image](https://cloud.githubusercontent.com/assets/344610/23284462/9c1ef1f2-fa23-11e6-8fd2-553672ee9ed7.png)

**Comment by julienrf** [comment]
Yeah, that’s a good point and should be fixed in a new version of scala-lang.org (to be published soon)

**Comment by heathermiller** [comment]
Yep, also a new version of the Scala Center website :)

**Comment by heathermiller** [comment]
This has been fixed for a while now :)
