### ISSUE TITLE
Fix "contributors are welcome" mouseovers

### ISSUE THREAD

**Issue by heathermiller** [scala/scala.epfl.ch#22]
<img width="307" alt="screen shot 2017-05-24 at 10 07 39 am" src="https://cloud.githubusercontent.com/assets/687163/26393032/dff2e416-4068-11e7-8c87-2afd19904758.png">

<img width="301" alt="screen shot 2017-05-24 at 10 08 30 am" src="https://cloud.githubusercontent.com/assets/687163/26393056/fc1994b4-4068-11e7-9e8d-feb6df043573.png">

<img width="300" alt="screen shot 2017-05-24 at 10 08 38 am" src="https://cloud.githubusercontent.com/assets/687163/26393061/fdca00aa-4068-11e7-862b-62032cfee39d.png">

**Comment by julienrf** [comment]
In my browser even without mouseovering I get a wrong layout:

![image](https://cloud.githubusercontent.com/assets/332812/26397786/bfb6ef62-4077-11e7-921b-8d96bf354696.png)

(Also commented in https://github.com/scala/scala.epfl.ch/commit/92bf3348b94cafb643c59b1bf6cfe8eb83822707#commitcomment-22260331)

**Comment by heathermiller** [comment]
Fixed this today
