### ISSUE TITLE
Update the status of SCP-011: currently marked as postponed but should be accepted

### ISSUE THREAD

**Issue by smarter** [scala/scala.epfl.ch#47]
https://github.com/scala/scala.epfl.ch/blob/master/minutes/_posts/2017-05-30-may-30-2017.md says:
> SCP-011: Debugging Position Information (Miles Sabin, on behalf of Lars Hupel)
> discussed; postponed for further consideration

But according to @fommil and @propensive, this proposal was subsequently accepted ([see gitter discussion](https://gitter.im/scala/tooling-contrib?at=5a057b87f7299e8f5395df5e)). We can find traces of this in https://github.com/scalacenter/advisoryboard/commit/1b7d21088a6f4efc31acc60d35055fda80038fe2 which contains the following Addendum that was not ported to this repository:

> ## Addendum
> 
> Following the meeting, it emerged that the criterion upon which a majority of
> attendees voted to postpone the acceptance vote of
> [SCP-011](https://github.com/scalacenter/advisoryboard/blob/master/proposals/011-debugging-symbols.md)
> (despite broad support)—that JetBrains (as the developers of the most popular
> IDE for Scala) should be involved in the discussion—was ill-founded, as
> JetBrains had worked closely with Sam Halliday in the drafting of the proposal.
> 
> This was not clear to the attendees in the meeting as GitHub (where many of
> JetBrains' could be seen) was not functioning at the time, and the member
> making the proposal (Lars Hupel) was unable to be present in the meeting.
> 
> Jon felt that had this been known during the meeting, many of the attendees
> would have voted differently, and subsequently invited all voting members of
> the board to review the decision to postpone the proposal. All voting members
> were informed of the new information, and asked firstly whether they would like
> to overturn the earlier decision to postpone the vote, and secondly (regardless
> of their answer to the first question), whether they vote to accept the
> proposal as a recommendation.
> 
> The respondents voted unanimously (with 3 abstentions) to overturn the decision
> to postpone the vote on the proposal, and voted 7-1 (with 3 abstentions) in
> favor of accepting the proposal as a recommendation.
> [SCP-011](https://github.com/scalacenter/advisoryboard/blob/master/proposals/011-debugging-symbols.md)
> has therefore been adopted as a recommendation.

**Comment by smarter** [comment]
Friendly 20 months ping :).

**Comment by SethTisue** [comment]
I'm actually not sure whose responsibility this change might currently be, if anybody's

**Comment by fommil** [comment]
Since Lars no longer has the seat, and Miles was a temporary replacement, perhaps @tpolecat to follow up with... somebody... ?

**Comment by SethTisue** [comment]
@sjrd let's close this out (@smarter pinged us on gitter today, thanks for the reminder)
