### ISSUE TITLE
Should the Github namespace be scalacenter?

### ISSUE THREAD

**Issue by jarrodu** [scala/scala.epfl.ch#59]
Hello. I noticed that the Scala Center has its own Github [account](https://github.com/scalacenter). I was thinking that this repo could be moved over there.

Any ideas @fsalvi?

**Comment by SethTisue** [comment]
@fsalvi assuming @heathermiller likes the idea, I assume the build script on your servers would just need slight tweaking...?

**Comment by fsalvi** [comment]
Yes, we would need to change the jenkins job.

**Comment by heathermiller** [comment]
I'd prefer to just keep this repo where it is, I suppose.
