### ISSUE TITLE
front page is missing new board members

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.epfl.ch#8]
SAP, Twitter, Tapad are all missing

**Comment by SethTisue** [comment]
Morgan Stanley

**Comment by heathermiller** [comment]
SAP and Tapad are there. Twitter hasn't signed the documents yet (very soon). And Morgan Stanley hasn't given us permission to post their logo anywhere, although we can mention them in the minutes.

**Comment by heathermiller** [comment]
I'm actually going to close this then, because we're waiting for permission to post Twitter's logo.
